spring:
  application:
    name: secure-banking-system

  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./bankdata;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:SA}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  server:
    port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:SecureBankingSystemSuperSecretKey256BitMinimumLengthForHMACSHA256}
    expiration-ms: 900000
    refresh-expiration-ms: 604800000

  encryption:
    aes-key: ${AES_KEY:1234567890123456}
    rsa-key-size: 2048

  fraud:
    max-daily-transfer: 100000.00
    suspicious-amount-threshold: 10000.00
    max-failed-login-attempts: 5
    lockout-duration-minutes: 30

  cors:
    allowed-origins: ${CORS_ORIGINS:*}

logging:
  level:
    com.securebank: INFO
    org.springframework.security: WARN